/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'RECOMMENDAI',systemName:'知华可解释智能推荐平台',englishName:'EXPLAINABLE AI RECOMMENDATION',theme:{primary:'#625a7c',dark:'#352f47',accent:'#c88448'},workspace:'数字增长中心 / 推荐策略组',fieldWorkspace:'零售事业部 / 推荐运营组',period:'2026-08-19 · 实时策略',liveText:'用户分群与库存于 10:41 更新',fieldContextLabel:'当前场景',fieldContext:'商城首页 · 新客首购',fieldUser:'唐悦',fieldRole:'推荐运营专员',adminUser:'孟川',adminRole:'数字增长负责人',
 adminTitle:'推荐策略运营中心',adminBreadcrumb:'数字增长 / 智能推荐',adminSubtitle:'融合用户分群、商品匹配、库存与业务目标，生成带理由、可控且可复盘的推荐顺序。',exportAction:'导出策略报告',createAction:'新建推荐实验',chartTitle:'推荐点击转化趋势',chartSubtitle:'实际转化率 / 实验目标',chartLabels:['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00'],loadTitle:'场景推荐负荷',loadSubtitle:'实验流量占策略容量',recordsTitle:'重点推荐实验',recordsSubtitle:'按业务影响、护栏命中和实验进度排序',issueTitle:'推荐策略事件',issueSubtitle:'需要运营、商品或合规共同确认',
 recordName:'推荐实验',itemName:'场景 / 客群',unitName:'运营团队',batchName:'策略版本',planName:'候选',doneName:'已计算',exceptionName:'拦截',unitLabel:'个',listBreadcrumb:'推荐运营 / 策略实验',listSubtitle:'管理候选召回、排序、业务护栏、人工审批和实验复盘。',listSummary:[['今日推荐','186万'],['在线实验','18'],['护栏拦截','42',true],['转化提升','8.6%']],tabs:['全部','待配置','运行中','待审批','已归档'],
 fieldBreadcrumb:'推荐工作台 / 零售运营',fieldTitle:'推荐策略工作台',fieldSubtitle:'我的实验 8 项 · 护栏事件 4 项 · 待审批 3 项',fieldSecondary:'查看客群画像',reportAction:'提交策略意见',fieldNoticeTitle:'特征与库存链路正常',fieldNotice:'实时特征新鲜度 98.6%',steps:['候选召回','可解释排序','业务护栏','流量实验','效果复盘'],documentAction:'查看推荐证据',printAction:'导出实验单',resourceCardTitle:'推荐计算资源',resourceValueLabel:'每秒请求',resourceHealthLabel:'服务健康度',quickSubtitle:'常用推荐入口',quickActions:[['策略反馈','/shopfloor/report','排序、护栏与运营意见'],['客群与商品','/shopfloor/material','分群、库存和业务目标'],['推荐资源','/shopfloor/resources','特征、排序和护栏服务'],['策略升级','/shopfloor/andon','敏感品类与重大异常']],
 reportDefaults:[8,1],reportTitle:'推荐策略反馈',reportSubtitle:'记录采纳顺序、业务依据和实验范围。',reportSuccess:'推荐策略意见已提交',reportPlaceholder:'填写客群判断、商品依据、护栏结果和实验建议',reportFootnote:'受限品类和重大流量变更必须经过授权人员确认',ruleTitle:'推荐安全护栏',ruleSubtitle:'RECOMMEND-AI · V1.0',rules:[['受限品类','禁止自动推荐'],['低库存商品','降低优先级'],['重复购买','设置冷却期'],['实验放量','分级审批',true]],fieldTotals:[['8','我的实验'],['4','护栏事件'],['3','待审批策略'],['98.6%','特征新鲜度']],
 adminMenus:[['/admin','home','推荐策略中心'],['/admin/work-orders','order','推荐实验'],['/admin/samples','box','客群与商品'],['/admin/schedule','calendar','实验日历'],['/admin/methods','process','排序策略'],['/admin/reviews','quality','策略审批'],['/admin/resources','machine','推荐资源'],['/admin/report','chart','效果分析']],fieldMenus:[['/shopfloor','home','推荐工作台'],['/shopfloor/report','report','策略反馈'],['/shopfloor/tasks','order','我的实验'],['/shopfloor/material','box','客群与商品'],['/shopfloor/resources','machine','服务状态'],['/shopfloor/andon','risk','策略升级',4]],moduleTitles:{tasks:['我的推荐实验','查看客群、候选和实验进度'],material:['客群与商品台账','查看分群、库存、毛利和业务目标'],resources:['推荐资源中心','管理特征、召回、排序和护栏服务'],andon:['推荐策略升级','提交敏感品类和重大效果异常'],samples:['推荐样本库','维护正负反馈与评测样本'],schedule:['推荐实验日历','协调流量、活动和版本窗口'],methods:['排序与护栏策略','维护匹配、业务目标和安全规则'],reviews:['推荐策略审批','记录采纳、调整和驳回意见'],report:['推荐效果分析','分析点击、转化、覆盖和多样性']},
 tagline:'让推荐更懂用户，也尊重库存与业务边界',storyTitle:'不是把商品强推给用户，<br/>而是提供有理由的候选顺序',storyText:'每条推荐都展示匹配、库存与护栏依据，运营人员保留最终实验和放量决策。',pattern:[2,4,7,10,13,16,19,22,25,28,31],loginStats:[['186万','今日推荐'],['8.6%','转化提升'],['42','护栏拦截']],loginTitle:'推荐策略运营中心',adminDemo:'客群 / 策略 / 实验',fieldDemo:'候选 / 护栏 / 反馈'}
export const records=[{no:'RC-260819-118',name:'新客家居首购推荐',code:'SEG-NEW-HOME',unit:'零售增长组',group:'消费事业部',plan:3200,done:2680,exception:36,due:'11:00',batch:'rank-v3.2',status:'运行中',progress:84,priority:'关注'},{no:'RC-260819-112',name:'商用滤芯交叉销售',code:'SEG-B2B-FILTER',unit:'推荐策略中心',group:'商用事业部',plan:1800,done:1220,exception:18,due:'12:00',batch:'cross-v2.1',status:'待审批',progress:68,priority:'正常'},{no:'RC-260819-106',name:'敏感品类推荐审查',code:'SEG-SENSITIVE',unit:'模型治理组',group:'AI 平台',plan:960,done:420,exception:42,due:'10:45',batch:'guard-v4.0',status:'策略复核',progress:44,priority:'紧急'},{no:'RC-260819-099',name:'日用消费稳定策略',code:'SEG-DAILY',unit:'零售增长组',group:'消费事业部',plan:2400,done:2400,exception:8,due:'08-18',batch:'rank-v3.1',status:'已归档',progress:100,priority:'正常'}]
export const resources=[{code:'PROFILE-01',name:'用户分群特征服务',unit:'数据平台组',status:'运行中',health:99,value:'98.6',valueUnit:'%',note:'实时特征低于 2 秒延迟'},{code:'RANK-02',name:'实时推荐排序引擎',unit:'推荐算法组',status:'运行中',health:96,value:'1,286',valueUnit:'RPS',note:'P95 响应 42 ms'},{code:'GUARD-03',name:'推荐安全护栏',unit:'模型治理组',status:'预警',health:91,value:'42',valueUnit:'项',note:'4 项受限品类等待确认'}]
export const reviews=[{no:'RV-260819-032',title:'敏感品类推荐审查',type:'受限品类审批',detail:'涉及 42 个候选 · 孟川',result:'待确认'},{no:'RV-260819-027',title:'日用消费稳定策略',type:'策略复盘',detail:'转化提升 6.2% · 唐悦',result:'通过'},{no:'RV-260819-018',title:'新客家居库存护栏',type:'库存复核',detail:'36 个候选库存偏低',result:'异常'}]
export const adminMetrics=[['今日推荐','186万','峰值 1,286 RPS','blue'],['转化提升','8.6%','对比基础策略','green'],['在线实验','18','覆盖 6 个场景','orange'],['护栏拦截','42','4 项需要人工确认','red']]
export const fieldMetrics=[['我的实验','8','3 项待审批','blue'],['今日已复盘','12','7 项达到目标','green'],['护栏事件','4','全部已停止放量','orange'],['特征新鲜度','98.6%','实时链路正常','slate']]
export const chartActual=[4.2,4.6,4.8,5.1,5.4,5.8,6.1,6.4,6.7],chartTarget=[4.5,4.7,5.0,5.3,5.6,5.9,6.2,6.5,6.8]
export const loads=[['商城首页',88,'实验 6 项'],['商品详情',76,'实验 5 项'],['购物车',62,'实验 4 项'],['消息触达',48,'实验 3 项']]
export const issues=[['护栏','敏感品类命中禁止推荐规则','相关候选已从在线列表移除','待确认'],['库存','家居候选库存覆盖不足 7 天','已降低排序优先级','处理中'],['效果','商用滤芯实验分群差异较大','建议延长观察周期','待评审']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
